name: Deploy to Google Container Registry (GCR)

on:
  push:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: GCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Configure Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: chrome-orb-446317-k6
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build Docker image
      run: docker build -t gcr.io/chrome-orb-446317-k6/demogo:latest .

    - name: Push Docker image to GCR
      run: docker push gcr.io/chrome-orb-446317-k6/demogo:latest
